---
.only-default: &only-default
  only:
    - master
    - wip
    - merge_requests
    - tags

flake8:
  <<: *only-default
  image: "alpine:latest"
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install flake8"
  script:
  - ".ci/flake8.sh"

shellcheck:
  <<: *only-default
  image: "alpine:latest"
  before_script:
  - "apk -q add shellcheck"
  script:
  - ".ci/shellcheck.sh"

install-pmbootstrap:
  <<: *only-default
  image: "alpine:latest"
  script:
  - "./install_pmbootstrap.sh"
  - su pmos -c "pmbootstrap chroot -- echo 'hello world'"

mr-settings:
  only:
    - merge_requests
  image: "alpine:latest"
  before_script:
    - "apk -q add python3"
  script:
    - "./check_mr_settings.py"
