---
flake8:
  image: "alpine:latest"
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install flake8"
  script:
  - ".ci/flake8.sh"

shellcheck:
  image: "alpine:latest"
  before_script:
  - "apk -q add shellcheck"
  script:
  - ".ci/shellcheck.sh"

install-pmbootstrap:
  image: "alpine:latest"
  script:
  - "./install_pmbootstrap.sh"
  - su pmos -c "pmbootstrap chroot -- echo 'hello world'"
